server:
  ssl:
    key-store: keystore.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-password: changeit
    enabled: false
    key-alias: samokatim
    enabled-protocols: TLSv1.2
spring:
  cloud:
    gateway:
      routes:
        - id: monitoring
          uri: http://localhost:8081
          predicates:
            - Path=/v1/track/**
        - id: handbook
          uri: http://localhost:8082
          predicates:
            - Path=/v1/handbook/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowCredentials: true
            allowedMethods:
              - GET
              - POST
              - PUT
              - OPTIONS
              - PATCH
              - DELETE
logging:
  level:
    root: debug