name: CI/CD

on:
  push:
    branches: [ "master", "develop", "feature/**" ]
  pull_request:
    branches: [ "master", "develop", "feature/**" ]

env:
  PROJECT_NAME: samokatim-gateway

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Executable gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: bootJar
      - name: Docker Hub login
        run: docker login --username ${{ secrets.USERNAME_HUB }} --password ${{ secrets.PASSWORD_HUB }}
      - name: Docker build
        run: docker build --tag ${{ secrets.USERNAME_HUB }}/$PROJECT_NAME:latest .
      - name: Docker push
        run: docker push ${{ secrets.USERNAME_HUB }}/$PROJECT_NAME:latest
  deployment:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Create SSH key file
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
      - name: Deploy to server
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -A ${{ secrets.BASTION_USER }}@${{ secrets.BASTION_HOST }} 'docker stop gateway; docker rm gateway; docker rmi muravevartem/samokatim-gateway; docker run -d --network backend -p 8080:8080 --name gateway muravevartem/samokatim-gateway:latest'
